# Base image is created by https://github.com/swift-nav/docker-recipes
FROM 571934480752.dkr.ecr.us-west-2.amazonaws.com/swift-tools-haskell:2019-05-14

# Add anything that's specific to this repo's build environment here.
